[package]
name = "orthrus"
version = "0.2.0"
authors = ["NWPlayer123 <nikki@aetheria.dev>"]
edition = "2021"
description = "A new way to modify games."
readme = "README.md"
repository = "https://github.com/NWPlayer123/Orthrus"
license = "MIT OR Apache-2.0"
keywords = ["modding", "gamedev"]

[profile.release]
strip = true
lto = "fat"
codegen-units = 1

[dependencies]
orthrus-helper = { version = "0.2", path = "crates/helper" }
orthrus-panda3d = { version = "0.1", path = "crates/panda3d" }
orthrus-yaz0 = { version = "0.2", path = "crates/yaz0" }

argp = "0.3"
enable-ansi-support = "0.2"
fern = "0.6"
log = "0.4"
owo-colors = "3.5"

[workspace]
members = ["crates/*"]

# Workspace members should have their own details, e.g. a version bump on yaz0 should not
# necessarily require a version bump on all other modules, along with their own authors since this
# repo will get very large in the future, with different people focusing on features in a specific
# module
[workspace.package]
license = "MIT OR Apache-2.0"
repository = "https://github.com/NWPlayer123/Orthrus"
