[package]
name = "orthrus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release-lto]
inherits = "release"
opt-level = "z"
strip = true
lto = "thin"
codegen-units = 1

[dependencies]
orthrus-yaz0 = { version = "0.1.0", path = "./yaz0" }
clap = { version = "3.2.19" }
