wrap_comments = true
format_code_in_doc_comments = true
comment_width = 100
doc_comment_code_block_width = 100
hex_literal_case = "Upper"
imports_granularity = "Module"
newline_style = "Windows"
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
