max_width = 110
wrap_comments = true
format_code_in_doc_comments = true
comment_width = 110
doc_comment_code_block_width = 110
hex_literal_case = "Upper"
imports_granularity = "Module"
newline_style = "Windows"
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
chain_width = 100
edition = "2021"
struct_lit_width = 70
fn_params_layout = "Compressed"
