comment_width = 110
condense_wildcard_suffixes = true
doc_comment_code_block_width = 110
fn_params_layout = "Compressed"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Upper"
inline_attribute_width = 110
imports_granularity = "Crate"
newline_style = "Unix"
#reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
wrap_comments = true
use_small_heuristics = "Max"
max_width = 110