[package]
name = "orthrus-panda3d"
version = "0.1.0"
edition = "2021"
description = "Orthrus module supporting the Panda3D engine"
license.workspace = true
repository.workspace = true

[dependencies]
orthrus-core = { version = "0.2.0", path = "../core" }

x509-parser = { version = "0.15", features = ["validate", "verify"] }

bitflags = "2.3"
compact_str = "0.7"
log = "0.4"
