[package]
name = "orthrus-panda3d"
version = "0.1.0"
edition = "2021"
description = "Orthrus module supporting the Panda3D engine"
license.workspace = true
repository.workspace = true

[dependencies]
orthrus-core = { version = "0.2", path = "../core" }

snafu = { version = "0.8", default-features = false }
num_enum = { version = "0.7", default-features = false }
approx = { version = "0.5", default-features = false }
bevy_math = { version = "0.14", default-features = false, features = ["approx"] }
der = { version = "0.7", optional = true }

# Bevy-Specific Assets
bevy_animation = { version = "0.14", optional = true }
bevy_app = { version = "0.14", optional = true }
bevy_asset = { version = "0.14", optional = true }
bevy_color = { version = "0.14", optional = true }
bevy_core = { version = "0.14", optional = true }
bevy_ecs = { version = "0.14", optional = true }
bevy_hierarchy = { version = "0.14", optional = true }
bevy_log = { version = "0.14", optional = true }
bevy_pbr = { version = "0.14", optional = true }
bevy_reflect = { version = "0.14", optional = true }
bevy_render = { version = "0.14", optional = true }
bevy_scene = { version = "0.14", optional = true }
bevy_tasks = { version = "0.14", optional = true }
bevy_transform = { version = "0.14", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }

hashbrown = "0.14"
bitflags = "2.6"

[features]
default = ["std"]
std = ["snafu/std"]
signature = ["der", "orthrus-core/certificate"]
bevy = [
    "bevy_animation",
    "bevy_app",
    "bevy_asset",
    "bevy_color",
    "bevy_core",
    "bevy_ecs",
    "bevy_hierarchy",
    "bevy_log",
    "bevy_pbr",
    "bevy_reflect",
    "bevy_render",
    "bevy_scene",
    "bevy_tasks",
    "bevy_transform",
    "serde",
]
identify = []
