[package]
name = "orthrus-panda3d"
version = "0.1.0"
edition = "2021"
description = "Orthrus module supporting the Panda3D engine"
license.workspace = true
repository.workspace = true

[dependencies]
orthrus-helper = { version = "0.2.0", path = "../helper" }
log = "0.4"
hashbrown = "0.14"
enumflags2 = "0.7"
rustls = "0.21"
x509-parser = { version = "0.15", features = ["validate", "verify"] }
