[package]
name = "orthrus-panda3d"
version = "0.1.0"
edition = "2021"
description = "Orthrus module supporting the Panda3D engine"
license.workspace = true
repository.workspace = true

[dependencies]
orthrus-core = { version = "0.2", path = "../core" }

snafu = { version = "0.8", default-features = false }
num_enum = { version = "0.7", default-features = false }
approx = { version = "0.5", default-features = false }
glam = { version = "0.28", default-features = false, features = ["approx"] }
der = { version = "0.7", optional = true }

# Bevy-Specific Assets
bevy_asset = { optional = true, git = "https://github.com/bevyengine/bevy.git", rev = "1db0214f245ebb65c35505fd05af4a6ebbf6b013" }
bevy_core = { optional = true, git = "https://github.com/bevyengine/bevy.git", rev = "1db0214f245ebb65c35505fd05af4a6ebbf6b013" }
bevy_ecs = { optional = true, git = "https://github.com/bevyengine/bevy.git", rev = "1db0214f245ebb65c35505fd05af4a6ebbf6b013" }
bevy_hierarchy = { optional = true, git = "https://github.com/bevyengine/bevy.git", rev = "1db0214f245ebb65c35505fd05af4a6ebbf6b013" }
bevy_log = { optional = true, git = "https://github.com/bevyengine/bevy.git", rev = "1db0214f245ebb65c35505fd05af4a6ebbf6b013" }
bevy_pbr = { optional = true, git = "https://github.com/bevyengine/bevy.git", rev = "1db0214f245ebb65c35505fd05af4a6ebbf6b013" }
bevy_reflect = { optional = true, git = "https://github.com/bevyengine/bevy.git", rev = "1db0214f245ebb65c35505fd05af4a6ebbf6b013" }
bevy_render = { optional = true, git = "https://github.com/bevyengine/bevy.git", rev = "1db0214f245ebb65c35505fd05af4a6ebbf6b013" }
bevy_scene = { optional = true, git = "https://github.com/bevyengine/bevy.git", rev = "1db0214f245ebb65c35505fd05af4a6ebbf6b013" }
serde = { version = "1.0", optional = true, features = ["derive"] }

hashbrown = "0.14"
bitflags = "2.6"

[features]
default = ["std"]
std = ["snafu/std", "glam/std"]
signature = ["der", "orthrus-core/certificate"]
bevy = [
    "bevy_asset",
    "bevy_core",
    "bevy_ecs",
    "bevy_hierarchy",
    "bevy_log",
    "bevy_pbr",
    "bevy_reflect",
    "bevy_render",
    "bevy_scene",
    "serde",
]
identify = []
