[package]
name = "orthrus-panda3d"
version = "0.1.0"
edition = "2021"
description = "Orthrus module supporting the Panda3D engine"
license.workspace = true
repository.workspace = true

[dependencies]
orthrus-core = { version = "0.2.0", path = "../core", features = ["certificate"] }

snafu = { version = "0.7", default-features = false }

der = "0.7"
x509-cert = "0.2"

bitflags = "2.3"

[features]
default = ["std"]
std = ["snafu/std"]
