[package]
name = "orthrus-panda3d"
version = "0.1.0"
edition = "2021"
description = "Orthrus module supporting the Panda3D engine"
license.workspace = true
repository.workspace = true

[dependencies]
orthrus-core = { version = "0.2.0", path = "../core", features = ["certificate", "time"] }

snafu = { version = "0.8", default-features = false }

der = { version = "0.7", optional = true }

bitflags = "2.3"

[features]
default = ["std"]
std = ["snafu/std"]
signature = ["der"]
