[package]
name = "orthrus-ncompress"
version = "0.2.0"
edition = "2021"
description = "Orthrus module supporting Nintendo compression formats"
license.workspace = true
repository.workspace = true

[dependencies]
orthrus-core = { version = "0.2.0", path = "../core" }

snafu = { version = "0.7", default-features = false }
log = "0.4"

[features]
default = ["std"]
std = ["snafu/std"]
