[package]
name = "orthrus-yaz0"
version = "0.2.0"
edition = "2021"
description = "Orthrus module supporting Yaz0 compression"
license.workspace = true
repository.workspace = true

[dependencies]
orthrus-core = { version = "0.2.0", path = "../core" }

log = "0.4"
