[package]
name = "orthrus-yaz0"
version = "0.1.0"
edition = "2021"
description = "Orthrus module supporting Yaz0 compression"
license.workspace = true
repository.workspace = true

[dependencies]
orthrus-helper = { version = "0.1.0", path = "../helper" }
