[package]
name = "orthrus-yaz0"
version = "0.1.0"
edition = "2021"

[lib]
name = "yaz0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orthrus-alloc = { version = "0.1.0", path = "../alloc" }
