[package]
name = "orthrus-core"
version = "0.2.0"
edition = "2021"
description = "Provides core functionality for Orthrus"
license.workspace = true
repository.workspace = true

[dependencies]
snafu = { version = "0.7", default-features = false }
time = { version = "0.3", features = ["formatting", "macros", "local-offset"], optional = true }
# compact_str = { version = "0.7", default-features = false, optional = true }
# x509-parser = { version = "0.15", features = ["validate", "verify"], optional = true }

# bitflags = { version = "2.4", optional = true }
# hashbrown = { version = "0.14", optional = true }
# log = { version = "0.4", optional = true }
# ouroboros = { version = "0.18", optional = true }
# thiserror = { version = "1.0", optional = true }

[features]
default = ["std"]
std = ["snafu/std"]
time = ["dep:time", "std"]