[package]
name = "orthrus-core"
version = "0.2.0"
edition = "2021"
description = "Provides core functionality for Orthrus"
license.workspace = true
repository.workspace = true

[dependencies]
snafu = { version = "0.7", default-features = false }
compact_str = { version = "0.7", default-features = false }
time = { version = "0.3", features = ["macros"] }
x509-parser = { version = "0.15", features = ["validate", "verify"], optional = true }

bitflags = "2.4"
hashbrown = "0.14"
log = "0.4"
ouroboros = "0.18"
thiserror = "1.0"

[features]
#TODO: work on no_std support
default = ["std"]
std = ["time/local-offset", "snafu/std", "x509-parser"]