[package]
name = "orthrus-core"
version = "0.2.0"
edition = "2021"
description = "Provides core functionality for Orthrus"
license.workspace = true
repository.workspace = true

[dependencies]
log = { version = "0.4", features = ["std"] }
time = { version = "0.3", features = ["formatting", "local-offset", "macros"] }
x509-parser = { version = "0.15", features = ["validate", "verify"] }

bitflags = "2.3"
compact_str = "0.7"
hashbrown = "0.14"
ouroboros = "0.17"
thiserror = "1.0"
