[package]
name = "orthrus-helper"
version = "0.2.0"
edition = "2021"
description = "Helper module for Orthrus"
license.workspace = true
repository.workspace = true

[dependencies]
hashbrown = "0.14.0"

